// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deecglfnjequyarcawsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZWNnbGZuamVxdXlhcmNhd3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjQ1NTYsImV4cCI6MjA3MzU0MDU1Nn0.wi1VQWzpVNGJlfLvHN9-ySvKvRaIWvJkFCotTh8QS8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});